### ISSUE TITLE
Is it a bug or just a typo in readme?

### ISSUE THREAD

**Issue by nimasdj** [lifo101/ip#1]
In readme

``` php
$ip = new CIDR('2001:4056::1/96');
echo "$ip\n", implode(' - ', $ip->getRange()), " (" . number_format($ip->getTotal()) . " hosts)\n";
```

why the output is shown as below?

```
2001:4056:: - 2001:4056::ffff:ffff (4,294,967,296 hosts)
```

Shouldn't it be as below instead?

```
2001:4056::1 - 2001:4056::ffff:ffff (4,294,967,296 hosts)
```

**Comment by lifo101** [comment]
See the comment in the readme:

```
// note: the true CIDR block is calculated from the prefix (the ::1 is ignored)
```

**Comment by nimasdj** [comment]
Sorry, would you please explain more? Prefix is not actually after / ? Why ::1 should be ignored?

**Comment by lifo101** [comment]
You're right, the wording is a little off. It should state "calculated from the prefix **length**". And I think some of this functionality may have changed a long time ago and the examples were never updated. 

By default `getRange()` will calculate the starting IP based on the prefix length defined on the IP string when it was created via `new CIDR("...")` so the range starts at **0** in this example.

If you call `getRange(true)` it'll return the original starting IP, or `2001:4056::1` in this case.

**Comment by nimasdj** [comment]
So if an ipv4 is given as below:
45.76.80.245/28
Does it return the start ip as below:
45.76.80.240

**Comment by lifo101** [comment]
Correct. Unless you call `getRange(true)`

**Comment by nimasdj** [comment]
What are outstanding missing features for example?

**Comment by lifo101** [comment]
Nothing in particular. Just things I originally thought might be useful that dealt with provisioning. It's personal preference. Please look at the code to make a judgement call yourself.

**Comment by nimasdj** [comment]
Which version should I define in composer.json?
"lifo101/ip" : "~*"
?

**Comment by lifo101** [comment]
Either simply run "composer require lifo/ip" or set the version to
"dev-master". I don't have any tagged versions at this time.

And it's "lifo/ip" as the package name.

-- Jason
